<?php

namespace Proxies\__CG__\persistence\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Purchase extends \persistence\Entity\Purchase implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'Style' => [parent::class, 'Style', null],
        "\0".'*'."\0".'User' => [parent::class, 'User', null],
        "\0".'*'."\0".'purchase_id' => [parent::class, 'purchase_id', null],
        "\0".'*'."\0".'purchasedAt' => [parent::class, 'purchasedAt', null],
        "\0".'*'."\0".'subtotal' => [parent::class, 'subtotal', null],
        "\0".'*'."\0".'total' => [parent::class, 'total', null],
        "\0".'*'."\0".'username' => [parent::class, 'username', null],
        'Style' => [parent::class, 'Style', null],
        'User' => [parent::class, 'User', null],
        'purchase_id' => [parent::class, 'purchase_id', null],
        'purchasedAt' => [parent::class, 'purchasedAt', null],
        'subtotal' => [parent::class, 'subtotal', null],
        'total' => [parent::class, 'total', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
