<?php

namespace Proxies\__CG__\persistence\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StyleDefault extends \persistence\Entity\StyleDefault implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'Style' => [parent::class, 'Style', null],
        "\0".'*'."\0".'background' => [parent::class, 'background', null],
        "\0".'*'."\0".'description' => [parent::class, 'description', null],
        "\0".'*'."\0".'font' => [parent::class, 'font', null],
        "\0".'*'."\0".'fontColor' => [parent::class, 'fontColor', null],
        "\0".'*'."\0".'fontSize' => [parent::class, 'fontSize', null],
        "\0".'*'."\0".'image' => [parent::class, 'image', null],
        "\0".'*'."\0".'name' => [parent::class, 'name', null],
        "\0".'*'."\0".'price' => [parent::class, 'price', null],
        "\0".'*'."\0".'template_id' => [parent::class, 'template_id', null],
        'Style' => [parent::class, 'Style', null],
        'background' => [parent::class, 'background', null],
        'description' => [parent::class, 'description', null],
        'font' => [parent::class, 'font', null],
        'fontColor' => [parent::class, 'fontColor', null],
        'fontSize' => [parent::class, 'fontSize', null],
        'image' => [parent::class, 'image', null],
        'name' => [parent::class, 'name', null],
        'price' => [parent::class, 'price', null],
        'template_id' => [parent::class, 'template_id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
