<?php

namespace Proxies\__CG__\persistence\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \persistence\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'Purchase' => [parent::class, 'Purchase', null],
        "\0".'*'."\0".'Style' => [parent::class, 'Style', null],
        "\0".'*'."\0".'Template' => [parent::class, 'Template', null],
        "\0".'*'."\0".'UserInfo' => [parent::class, 'UserInfo', null],
        "\0".'*'."\0".'UserPhone' => [parent::class, 'UserPhone', null],
        "\0".'*'."\0".'UserSocial' => [parent::class, 'UserSocial', null],
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".'*'."\0".'defaultTemplate' => [parent::class, 'defaultTemplate', null],
        "\0".'*'."\0".'deleteToken' => [parent::class, 'deleteToken', null],
        "\0".'*'."\0".'email' => [parent::class, 'email', null],
        "\0".'*'."\0".'password' => [parent::class, 'password', null],
        "\0".'*'."\0".'token' => [parent::class, 'token', null],
        "\0".'*'."\0".'username' => [parent::class, 'username', null],
        'Purchase' => [parent::class, 'Purchase', null],
        'Style' => [parent::class, 'Style', null],
        'Template' => [parent::class, 'Template', null],
        'UserInfo' => [parent::class, 'UserInfo', null],
        'UserPhone' => [parent::class, 'UserPhone', null],
        'UserSocial' => [parent::class, 'UserSocial', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'defaultTemplate' => [parent::class, 'defaultTemplate', null],
        'deleteToken' => [parent::class, 'deleteToken', null],
        'email' => [parent::class, 'email', null],
        'password' => [parent::class, 'password', null],
        'token' => [parent::class, 'token', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
