/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as AtuploadRouteImport } from './@upload'
import { Route as AtpriceRouteImport } from './@price'
import { Route as IndexRouteImport } from './index'

const AtuploadRoute = AtuploadRouteImport.update({
  id: '/@upload',
  path: '/@upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AtpriceRoute = AtpriceRouteImport.update({
  id: '/@price',
  path: '/@price',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/@price': typeof AtpriceRoute
  '/@upload': typeof AtuploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/@price': typeof AtpriceRoute
  '/@upload': typeof AtuploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/@price': typeof AtpriceRoute
  '/@upload': typeof AtuploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/@price' | '/@upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/@price' | '/@upload'
  id: '__root__' | '/' | '/@price' | '/@upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtpriceRoute: typeof AtpriceRoute
  AtuploadRoute: typeof AtuploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/@upload': {
      id: '/@upload'
      path: '/@upload'
      fullPath: '/@upload'
      preLoaderRoute: typeof AtuploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@price': {
      id: '/@price'
      path: '/@price'
      fullPath: '/@price'
      preLoaderRoute: typeof AtpriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtpriceRoute: AtpriceRoute,
  AtuploadRoute: AtuploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
